name: Run Tests

on: push

env:
  TEST_DIR: test

jobs:
  hello-world:
    name: Hello world
    runs-on: ubuntu-latest
    steps:
    - name: Run Test
      run: python ${{ env.TEST_DIR }}/test.py .
      shell: sh
